#!/usr/bin/env python3
"""Reward functions for training transparent reasoning models with GRPO.

This module is the canonical, unit-tested implementation of the reward
functions used by ``tunix_reasoning_trainer.ipynb``. It is dependency-free
(standard library only) so it can be imported anywhere -- in the training
notebook, in evaluation scripts, or in your own GRPO pipeline.

The model is trained to emit answers in the following structured format::

    <reasoning>
    ...step-by-step reasoning...
    </reasoning>
    <answer>
    ...final answer...
    </answer>

Three reward components score a response:

* :func:`format_reward` -- did the model use the reasoning/answer tags?
* :func:`correctness_reward` -- does the extracted answer match the target?
* :func:`reasoning_quality_reward` -- is the reasoning substantive?

:func:`compute_reward` combines them into a single scalar using the weights in
:class:`RewardConfig`.

Example
-------
>>> response = "<reasoning>0.15 * 240 = 36</reasoning><answer>36</answer>"
>>> round(compute_reward(response, "36"), 3)
0.88
"""

from __future__ import annotations

import re
from dataclasses import dataclass

__all__ = [
    "RewardConfig",
    "extract_reasoning_and_answer",
    "format_reward",
    "correctness_reward",
    "reasoning_quality_reward",
    "compute_reward",
]

_REASONING_RE = re.compile(r"<reasoning>(.*?)</reasoning>", re.DOTALL)
_ANSWER_RE = re.compile(r"<answer>(.*?)</answer>", re.DOTALL)
_STEP_PATTERNS = (
    "first", "then", "next", "finally", "step", "therefore", "so", "because",
)
_MATH_PATTERNS = (
    r"\d+\s*[+\-*/]\s*\d+", r"=", r"multiply", r"divide", r"add", r"subtract",
)


@dataclass(frozen=True)
class RewardConfig:
    """Weights for combining the individual reward components.

    The defaults match the values documented in the project README and used in
    the training notebook. Weights are expected to sum to ``1.0`` but this is
    not enforced -- you are free to emphasise whichever signal matters most for
    your task.
    """

    format_reward_weight: float = 0.3
    correctness_reward_weight: float = 0.5
    reasoning_quality_weight: float = 0.2


def extract_reasoning_and_answer(response: str) -> tuple[str, str]:
    """Pull the reasoning and answer text out of a model response.

    Args:
        response: Raw text generated by the model.

    Returns:
        A ``(reasoning, answer)`` tuple. Either element is an empty string if
        its corresponding tag is missing.
    """
    reasoning_match = _REASONING_RE.search(response)
    answer_match = _ANSWER_RE.search(response)

    reasoning = reasoning_match.group(1).strip() if reasoning_match else ""
    answer = answer_match.group(1).strip() if answer_match else ""
    return reasoning, answer


def format_reward(response: str) -> float:
    """Reward correct use of the structured output format.

    Returns ``1.0`` when both ``<reasoning>`` and ``<answer>`` blocks are
    present, ``0.5`` when exactly one is present, and ``0.0`` otherwise.
    """
    has_reasoning = bool(_REASONING_RE.search(response))
    has_answer = bool(_ANSWER_RE.search(response))

    if has_reasoning and has_answer:
        return 1.0
    if has_reasoning or has_answer:
        return 0.5
    return 0.0


def correctness_reward(response: str, expected_answer: str) -> float:
    """Reward an answer that matches ``expected_answer``.

    Comparison is tolerant: it first tries an exact case-insensitive match,
    then a numerical match (ignoring units/punctuation, within ``0.01``), and
    finally a substring match worth partial credit.

    Returns a value in ``[0.0, 1.0]``.
    """
    _, extracted_answer = extract_reasoning_and_answer(response)
    if not extracted_answer:
        return 0.0

    extracted_normalized = extracted_answer.lower().strip()
    expected_normalized = expected_answer.lower().strip()

    # Exact (normalized) match.
    if extracted_normalized == expected_normalized:
        return 1.0

    # Numerical match, ignoring units and punctuation.
    extracted_clean = re.sub(r"[^0-9.-]", "", extracted_normalized)
    expected_clean = re.sub(r"[^0-9.-]", "", expected_normalized)
    try:
        if extracted_clean and expected_clean:
            if abs(float(extracted_clean) - float(expected_clean)) < 0.01:
                return 1.0
    except ValueError:
        pass

    # Partial credit when the expected answer appears within the response.
    if expected_normalized in extracted_normalized:
        return 0.7

    return 0.0


def reasoning_quality_reward(response: str) -> float:
    """Reward substantive, step-by-step reasoning.

    Rewards reasoning of a sensible length that contains step indicators
    ("first", "then", "therefore", ...), shows mathematical/logical work, and
    is composed of multiple sentences. Returns a value in ``[0.0, 1.0]``.
    """
    reasoning, _ = extract_reasoning_and_answer(response)
    if not reasoning:
        return 0.0

    score = 0.0

    # Length: reward a sensible amount of explanation.
    word_count = len(reasoning.split())
    if 10 <= word_count <= 200:
        score += 0.3
    elif word_count > 5:
        score += 0.1

    # Step indicators.
    step_matches = sum(
        1 for p in _STEP_PATTERNS if re.search(p, reasoning, re.IGNORECASE)
    )
    score += min(0.3, step_matches * 0.1)

    # Evidence of mathematical/logical work.
    math_matches = sum(
        1 for p in _MATH_PATTERNS if re.search(p, reasoning, re.IGNORECASE)
    )
    score += min(0.2, math_matches * 0.1)

    # Coherence: multiple sentences.
    if len(reasoning.split(".")) >= 2:
        score += 0.2

    return min(1.0, score)


def compute_reward(
    response: str,
    expected_answer: str,
    config: RewardConfig | None = None,
) -> float:
    """Combine the three reward components into a single weighted scalar.

    Args:
        response: Raw model output.
        expected_answer: Ground-truth answer for correctness scoring.
        config: Reward weights. Defaults to :class:`RewardConfig`.

    Returns:
        The weighted total reward.
    """
    config = config or RewardConfig()
    return (
        config.format_reward_weight * format_reward(response)
        + config.correctness_reward_weight * correctness_reward(response, expected_answer)
        + config.reasoning_quality_weight * reasoning_quality_reward(response)
    )


if __name__ == "__main__":
    demo = (
        "<reasoning>\n"
        "To find 15% of 240, convert 15% to 0.15, then multiply: "
        "0.15 * 240 = 36.\n"
        "</reasoning>\n"
        "<answer>36</answer>"
    )
    print(f"format_reward            = {format_reward(demo):.2f}")
    print(f"correctness_reward       = {correctness_reward(demo, '36'):.2f}")
    print(f"reasoning_quality_reward = {reasoning_quality_reward(demo):.2f}")
    print(f"compute_reward (total)   = {compute_reward(demo, '36'):.2f}")
